#!/bin/bash

#http://askubuntu.com/questions/129182/how-can-i-duplicate-my-existing-software-packages-on-a-new-system?rq=1

#duplicate a package set. On the old machine

#Copy the file packages to the new machine (a pen drive is a good option. Then run this:
sudo dpkg --get-selections "*" > packages




sudo apt-get update
sudo dpkg --set-selections < packages
sudo apt-get -u dselect-upgrade
