var DISQUS=function(b){var f=b.DISQUS||{};f.AssertionError=function(d){this.message=d};f.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};f.assert=function(d,g,c){if(!d)if(c)b.console&&b.console.log("DISQUS assertion failed: "+g);else throw new f.AssertionError(g);};var d=[];f.define=function(e,g){typeof e==="function"&&(g=e,e="");for(var c=e.split("."),h=c.shift(),a=f,l=(g||function(){return{}}).call({overwrites:function(a){a.__overwrites__=!0;
return a}},b);h;)a=a[h]?a[h]:a[h]={},h=c.shift();for(var j in l)l.hasOwnProperty(j)&&(!l.__overwrites__&&a[j]!==null&&f.assert(!a.hasOwnProperty(j),"Unsafe attempt to redefine existing module: "+j,!0),a[j]=l[j],d.push(function(a,d){return function(){delete a[d]}}(a,j)));return a};f.use=function(d){return f.define(d)};f.cleanup=function(){for(var e=0;e<d.length;e++)d[e]()};return f}(window);
DISQUS.define(function(b,f){var d=b.DISQUS,e=b.document,g=e.getElementsByTagName("head")[0]||e.body,c={running:!1,timer:null,queue:[]},h=0;d.getUid=function(a){var d=++h+"";return a?a+d:d};d.defer=function(a,d){function g(){var a=c.queue;if(a.length===0)c.running=!1,clearInterval(c.timer);for(var d=0,l;l=a[d];d++)l[0]()&&(a.splice(d--,1),l[1]())}c.queue.push([a,d]);g();if(!c.running)c.running=!0,c.timer=setInterval(g,100)};d.each=function(a,d){var g=a.length,c=Array.prototype.forEach;if(isNaN(g))for(var h in a)a.hasOwnProperty(h)&&
d(a[h],h,a);else if(c)c.call(a,d);else for(c=0;c<g;c++)d(a[c],c,a)};d.extend=function(a){d.each(Array.prototype.slice.call(arguments,1),function(d){for(var c in d)a[c]=d[c]});return a};d.serializeArgs=function(a){var c=[];d.each(a,function(a,d){a!==f&&c.push(d+(a!==null?"="+encodeURIComponent(a):""))});return c.join("&")};d.isString=function(a){return Object.prototype.toString.call(a)==="[object String]"};d.serialize=function(a,c,g){c&&(a+=~a.indexOf("?")?a.charAt(a.length-1)=="&"?"":"&":"?",a+=d.serializeArgs(c));
if(g)return c={},c[(new Date).getTime()]=null,d.serialize(a,c);c=a.length;return a.charAt(c-1)=="&"?a.slice(0,c-1):a};d.require=function(a,c,h,b,f){function n(a){if(a.type=="load"||/^(complete|loaded)$/.test(a.target.readyState))b&&b(),q&&clearTimeout(q),d.bean.remove(a.target,r,n)}var o=e.createElement("script"),r=o.addEventListener?"load":"readystatechange",q=null;o.src=d.serialize(a,c,h);o.async=!0;o.charset="UTF-8";(b||f)&&d.bean.add(o,r,n);f&&(q=setTimeout(function(){f()},2E4));g.appendChild(o);
return d};d.requireStylesheet=function(a,c,h){var b=e.createElement("link");b.rel="stylesheet";b.type="text/css";b.href=d.serialize(a,c,h);g.appendChild(b);return d};d.requireSet=function(a,c,g){var h=a.length;d.each(a,function(a){d.require(a,{},c,function(){--h===0&&g()})})};d.injectCss=function(a){var c=e.createElement("style");c.setAttribute("type","text/css");a=a.replace(/\}/g,"}\n");b.location.href.match(/^https/)&&(a=a.replace(/http:\/\//g,"https://"));c.styleSheet?c.styleSheet.cssText=a:c.appendChild(e.createTextNode(a));
g.appendChild(c)};d.isString=function(a){return Object.prototype.toString.call(a)==="[object String]"}});
DISQUS.define("JSON",function(){function b(a){return a<10?"0"+a:a}function f(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var c=j[a];return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function d(c,h){var b,e,k,n,j=a,p,i=h[c];i&&typeof i==="object"&&typeof i.toJSON==="function"&&!g&&(i=i.toJSON(c));typeof m==="function"&&(i=m.call(h,c,i));switch(typeof i){case "string":return f(i);case "number":return isFinite(i)?String(i):"null";case "boolean":case "null":return String(i);
case "object":if(!i)return"null";a+=l;p=[];if(Object.prototype.toString.apply(i)==="[object Array]"){n=i.length;for(b=0;b<n;b+=1)p[b]=d(b,i)||"null";k=p.length===0?"[]":a?"[\n"+a+p.join(",\n"+a)+"\n"+j+"]":"["+p.join(",")+"]";a=j;return k}if(m&&typeof m==="object"){n=m.length;for(b=0;b<n;b+=1)e=m[b],typeof e==="string"&&(k=d(e,i))&&p.push(f(e)+(a?": ":":")+k)}else for(e in i)Object.hasOwnProperty.call(i,e)&&(k=d(e,i))&&p.push(f(e)+(a?": ":":")+k);k=p.length===0?"{}":a?"{\n"+a+p.join(",\n"+a)+"\n"+
j+"}":"{"+p.join(",")+"}";a=j;return k}}var e={},g=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var c=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,a,l,j={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},m;e.stringify=function(c,g,b){var h;l=a="";if(typeof b==="number")for(h=0;h<b;h+=1)l+=" ";else typeof b==="string"&&(l=b);if((m=g)&&typeof g!=="function"&&(typeof g!=="object"||typeof g.length!=="number"))throw Error("JSON.stringify");return d("",{"":c})};e.parse=function(a,d){function g(a,
c){var b,h,e=a[c];if(e&&typeof e==="object")for(b in e)Object.hasOwnProperty.call(e,b)&&(h=g(e,b),h!==void 0?e[b]=h:delete e[b]);return d.call(a,c,e)}var b,a=String(a);c.lastIndex=0;c.test(a)&&(a=a.replace(c,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return b=eval("("+a+")"),
typeof d==="function"?g({"":b},""):b;throw new SyntaxError("JSON.parse");};var k={a:[1,2,3]},n,o;if(Object.toJSON&&Object.toJSON(k).replace(/\s/g,"")==='{"a":[1,2,3]}')n=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(k='{"a":[1,2,3]}'.evalJSON(),k.a&&k.a.length===3&&k.a[2]===3&&(o=function(a){return a.evalJSON()}));(function(){var a=[1,2,3];typeof a.toJSON==="function"&&(a=a.toJSON(),g=!(a&&a.length===3&&a[2]===3))})();if(g||!n||!o)return{stringify:e.stringify,parse:e.parse};return{stringify:n,
parse:o}});
DISQUS.define("Bus",function(){function b(c){c=c.split("/");return c[0]+"//"+c[2]}var f=DISQUS.use("JSON"),d=window.location.hash.slice(1),e=window.opener||window.parent,g=document.referrer,c={};c.client=b(document.location.href);c.host=g?b(g):c.client;return{origins:c,messageHandler:function(d){var a;try{a=DISQUS.JSON.parse(d.data)}catch(b){return}if(!a.name||!(a.name[0]==="!"&&d.origin!==c.client))switch(a.scope){case "client":DISQUS.Bus.trigger(a.name,a.data)}},postMessage:function(c){c.sender=d;
c=f.stringify(c);e.postMessage(c,"*")},sendHostMessage:function(c,a){a=a||[];DISQUS.Bus.postMessage({scope:"host",name:c,data:a})},sendGlobalMessage:function(c,a){a=a||[];DISQUS.Bus.postMessage({scope:"global",name:c,data:a})}}});_.extend(DISQUS.Bus,Backbone.Events);
$(document).ready(function(){var b=window.addEventListener?window.addEventListener:window.attachEvent,f=window.addEventListener?"message":"onmessage";if(!b)throw Error("No event support.");b(f,DISQUS.Bus.messageHandler,!1);window.onunload=function(){DISQUS.Bus.sendHostMessage("die")}});
DISQUS.define(function(){var b={apiKey:"E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F",debug:!1,browser:{mobile:/iPhone|Android|iPod|iPad|webOS|Mobile Safari|Windows Phone|BlackBerry|Opera Mini|IEMobile/i.test(navigator.userAgent)}};if(typeof require!=="undefined"&&typeof require==="function")b.bean=require("bean");return b});
DISQUS.define("strings",function(){function b(b){var g=d[b];return g!==void 0?g:b}function f(d,b){return d.replace(/%\(\w+\)s/g,function(c){var c=c.slice(2,-2),h="";c in b?h=b[c]!==void 0&&b[c]!==null?b[c].toString():"":DISQUS.logError&&DISQUS.logError("Key `"+c+"` not found in context for: ",d);return h})}var d={};DISQUS.interpolate=f;DISQUS.modules={};window.gettext=b;return{get:b,interpolate:f,translations:d}});
DISQUS.define("time",function(){return{ISO_8601:"YYYY-MM-DDTHH:mm:ssZ",assureTzOffset:function(b){return b.indexOf("+")>=0?b:b+"+00:00"}}});
DISQUS.define("urls",function(){var b=DISQUS.debug?"/js/src/embed/next/vglnk.js":"/build/next/alfie.js",f=encodeURIComponent(document.referrer),d={root:"http://disqus.com",media:"http://mediacdn.disqus.com/1372380899",translations:"http://mediacdn.disqus.com/1372380899/build/lang",loading:"http://mediacdn.disqus.com/1372380899/html/simple-loading.html",realertime:"",juggler:"",login:"https://disqus.com/next/login/",api:"http://disqus.com/api/3.0/",apiSecure:"https://disqus.com/api/3.0/",logout:"http://disqus.com/logout/?redirect="+
f,editProfile:"http://disqus.com/account/",verifyEmail:"https://disqus.com/next/verify/",authorize:"https://disqus.com/api/oauth/2.0/authorize/",redirectUrl:"//redirect.disqus.com/url",moderate:"http://disqus.com/admin/moderate/",oauth:{twitter:"http://disqus.com/_ax/twitter/begin/",google:"http://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"http://mediacdn.disqus.com/1372380899/images/noavatar92.png"},linkAffiliatorClient:"http://mediacdn.disqus.com/1372380899"+
b};window.location.protocol==="https:"&&(d=_.extend(d,{root:"https://disqus.com",media:"https://securecdn.disqus.com/1372380899",translations:"https://securecdn.disqus.com/1372380899/build/lang",loading:"/html/simple-loading.html",api:d.apiSecure,logout:"https://disqus.com/logout/?redirect="+f,editProfile:"https://disqus.com/account/",moderate:"https://disqus.com/admin/moderate/",oauth:{twitter:"https://disqus.com/_ax/twitter/begin/",google:"https://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},
avatar:{generic:"/images/noavatar92.png"},linkAffiliatorClient:""+b}));return d});DISQUS.define("templates",function(){function b(d,b){return Handlebars.partials[d](b||{},{data:f})}var f={urls:DISQUS.urls,gettext:DISQUS.strings.get,sso:null};DISQUS.renderBlock=b;DISQUS.templateGlobals=f;return{globals:f,render:b}});
DISQUS.define("api",function(){function b(d){function c(a){var f=a.originalEvent.origin;DISQUS.urls.apiSecure.slice(0,f.length)===f&&(a=DISQUS.JSON.parse(a.originalEvent.data),a.requestId===b&&(f=a.code===0?d.success:d.error,delete a.requestId,(f||function(){})(a),document.body.removeChild(m),document.body.removeChild(e),$(window).off("message",c)))}var b=_.uniqueId("ft_"),a=document.createElement("div"),e=document.createElement("form"),f="frame_"+b,m;a.innerHTML='<iframe name="'+f+'"></iframe>';
m=a.childNodes[0];e.target=f;e.action=d.url.replace(".json",".pm");e.method=d.method||"GET";d.data=_.extend(d.data,{callback:b,referrer:document.referrer});_.each(d.data,function(a,c){a===!0?a=[1]:a===!1?a=[0]:a===null?a=[""]:_.isArray(a)||(a=[a]);_.each(a,function(a){var d=document.createElement("input");d.type="hidden";d.name=c;d.value=a;e.appendChild(d)})});$(window).on("message",c);document.body.appendChild(m);document.body.appendChild(e);e.submit()}function f(b){b=_.defaults(b,d);b.data=b.data||
{};b.data.api_key=DISQUS.apiKey;return $.ajax(b)}var d={},e={defaults:function(b){var c,e,a;for(c in b)e=b[c],a=d[c],_.isObject(e)&&_.isObject(a)?_.extend(a,e):d[c]=e},headers:function(b){b=_.extend({},d.headers,b);d.headers=_.pick(b,_.map(b,function(c,b){if(c)return b}));return d.headers},getURL:function(b,c){c=c||{};if(c.secure||window.location.protocol==="https:")return DISQUS.urls.apiSecure+b;return DISQUS.urls.api+b},ajax:f,call:function(d,c){c=c||{};c.url=DISQUS.api.getURL(d,{secure:c.secure});
c.data=_.extend(c.data||{},{api_key:DISQUS.apiKey});this.trigger("call",c);var e=(c.secure?b:f)(c);e&&e.always(_.bind(this.trigger,this,"complete"));return e}};_.extend(e,Backbone.Events);return e});
(function(b){var f=DISQUS.Bus,d=DISQUS.api.getURL("internal/switches/list.jsonp");b.switches_jsonp_cb=function(b){f.sendHostMessage("switches.received",b.response)};f.on("fetch",function(b){b=b||{};b.data=b.data||{};b.data.callback="switches_jsonp_cb";b.data.api_key=DISQUS.apiKey;b=DISQUS.serialize(d,b.data,!1);DISQUS.require(b)});f.sendHostMessage("ready")})(this);