(function(){var l=Handlebars.template;(Handlebars.discovery=Handlebars.discovery||{}).templates=l(function(g,k,d,h,a){function b(a,e,w){var c="",b;c+='\n        <section id="';(b=d.id)?b=b.call(a,{hash:{},data:e}):(b=a.id,b=typeof b===r?b.apply(a):b);c+=o(b)+'" class="';(b=d.className)?b=b.call(a,{hash:{},data:e}):(b=a.className,b=typeof b===r?b.apply(a):b);c+=o(b)+'">\n            <header class="discovery-col-header">\n\n                ';if((b=d["if"].call(a,e.index===e.length-1,{hash:{},inverse:i.noop,
fn:i.program(3,q,e),data:e}))||b===0)c+=b;c+="\n\n                ";if((b=d["if"].call(a,a.type==="organic",{hash:{},inverse:i.noop,fn:i.programWithDepth(f,e,w),data:e}))||b===0)c+=b;c+="\n                ";if((b=d["if"].call(a,a.type==="promoted",{hash:{},inverse:i.noop,fn:i.program(7,m,e),data:e}))||b===0)c+=b;c+='\n\n            </header>\n            <ul class="discovery-posts">\n            </ul>\n        </section>\n    ';return c}function q(a,e){var b="";b+='\n                    \n                    <div class="discovery-options">\n                        <span class="publisher-anchor-color"><a href="#" class="discovery-help" data-action="discovery-help">'+
o(d.t.call(a,gettext("What's this?"),{hash:{},data:e}))+"</a></span>\n                    </div>\n                ";return b}function f(a,e,b){var c="";c+="\n                    <h2>"+o(d.t.call(a,gettext("Also on %(forumName)s"),{hash:{forumName:{partial:"forumName",context:b.forum,executePartial:!0}},data:e}))+"</h2>\n                ";return c}function m(a,e){var b="";b+="\n                    <h2>"+o(d.t.call(a,gettext("Around The Web"),{hash:{},data:e}))+"</h2>\n                ";return b}function e(a,
e,b){var c="",f,j;c+='\n        <li class="discovery-post" id="discovery-link-';(f=d.domIdSuffix)?f=f.call(a,{hash:{},data:e}):(f=a.domIdSuffix,f=typeof f===r?f.apply(a):f);c+=o(f)+'">\n            <header class="discovery-post-header">\n                <h3 title="';(f=d.title)?f=f.call(a,{hash:{},data:e}):(f=a.title,f=typeof f===r?f.apply(a):f);c+=o(f)+'">\n                    <a ';if((f=i.invokePartial(h.linkAttributes,"linkAttributes",a,d,h,e))||f===0)c+=f;c+=' data-role="discovery-thread-title" class="title publisher-anchor-color line-truncate" data-line-truncate="2">\n                        '+
o(d.html.call(a,a.title,{hash:{},data:e}))+"\n                    </a>\n\n                    ";if((j=d["if"].call(a,(f=b.variant,f==null||f===!1?f:f.inlineMeta),{hash:{},inverse:i.noop,fn:i.program(17,v,e),data:e}))||j===0)c+=j;c+="\n\n                </h3>\n\n                ";if((j=d.unless.call(a,(f=b.variant,f==null||f===!1?f:f.inlineMeta),{hash:{},inverse:i.noop,fn:i.program(25,s,e),data:e}))||j===0)c+=j;c+="\n\n            </header>\n\n            ";if((j=d["if"].call(a,(f=b.variant,f==null||
f===!1?f:f.contentPreviews)&&a.preview,{hash:{},inverse:i.noop,fn:i.program(30,x,e),data:e}))||j===0)c+=j;c+="\n\n        </li>\n    ";return c}function v(a,e){var b="",c;b+="\n                        ";if((c=d["if"].call(a,a.posts>0,{hash:{},inverse:i.program(20,t,e),fn:i.program(18,j,e),data:e}))||c===0)b+=c;b+="\n                        ";if((c=d["if"].call(a,a.brand,{hash:{},inverse:i.noop,fn:i.program(23,n,e),data:e}))||c===0)b+=c;b+="\n                    ";return b}function j(a,e){var b="",
c;b+='\n                            <span class="inline-meta">\n                                ';if((c=i.invokePartial(h.discoveryPostCount,"discoveryPostCount",a,d,h,e))||c===0)b+=c;b+="\n                            </span>\n                        ";return b}function t(a,e){var b="",c;b+="\n                            ";if((c=d["if"].call(a,a.createdAgo,{hash:{},inverse:i.noop,fn:i.program(21,y,e),data:e}))||c===0)b+=c;b+="\n                        ";return b}function y(a,e){var b="",c;b+='\n                                <span class="inline-meta">';
(c=d.createdAgo)?c=c.call(a,{hash:{},data:e}):(c=a.createdAgo,c=typeof c===r?c.apply(a):c);b+=o(c)+"</span>\n                            ";return b}function n(a,e){var b="",c;b+='\n                            <span class="inline-meta">\n                                ';(c=d.brand)?c=c.call(a,{hash:{},data:e}):(c=a.brand,c=typeof c===r?c.apply(a):c);b+=o(c)+"\n                            </span>\n                        ";return b}function s(a,e){var b="",c;b+='\n                    <ul class="meta">\n                        ';
if((c=d["if"].call(a,a.posts>0,{hash:{},inverse:i.noop,fn:i.program(26,z,e),data:e}))||c===0)b+=c;b+="\n                        ";if((c=d["if"].call(a,a.createdAgo,{hash:{},inverse:i.noop,fn:i.program(28,l,e),data:e}))||c===0)b+=c;b+="\n                    </ul>\n                ";return b}function z(a,e){var b="",c;b+='\n                            <li class="comments">\n                                ';if((c=i.invokePartial(h.discoveryPostCount,"discoveryPostCount",a,d,h,e))||c===0)b+=c;b+="\n                            </li>\n                        ";
return b}function l(a,e){var b="",c;b+='\n                            <li class="time">';(c=d.createdAgo)?c=c.call(a,{hash:{},data:e}):(c=a.createdAgo,c=typeof c===r?c.apply(a):c);b+=o(c)+"</li>\n                        ";return b}function x(a,b){var e="",c;e+="\n                ";if((c=i.invokePartial(h.discoveryContentPreview,"discoveryContentPreview",a,d,h,b))||c===0)e+=c;e+="\n            ";return e}function A(){return'target="_blank" rel="nofollow"'}function B(a,e){var b="";b+="\n        "+o(d.t.call(a,
gettext("1 comment"),{hash:{},data:e}))+"\n    ";return b}function C(a,e){var b="";b+="\n        "+o(d.t.call(a,gettext("%(numPosts)s comments"),{hash:{numPosts:a.posts},data:e}))+"\n    ";return b}this.compilerInfo=[2,">= 1.0.0-rc.3"];var d=d||g.helpers,h=h||g.partials,a=a||{},g="",p,o=this.escapeExpression,r="function",i=this;if((p=d.partial.call(k,"discoveryMain",{hash:{},inverse:i.noop,fn:i.programWithDepth(function(a,e,f){var c="",j;c+='\n<div id="';(j=d.id)?j=j.call(a,{hash:{},data:e}):(j=a.id,
j=typeof j===r?j.apply(a):j);c+=o(j)+'" class="discovery-main">\n    <div id="discovery-note" style="display:none;">\n        <div class="alert">\n        <a href="#" class="close" data-action="discovery-help-close" title="'+o(d.t.call(a,gettext("Close this box"),{hash:{},data:e}))+'">\u00d7</a>\n        '+o(d.t.call(a,gettext("Disqus helps you find new and interesting content, discussions and products. Some sponsors and ecommerce sites may pay us for these recommendations and links. %(learnMore)s or %(feedback)s."),
{hash:{learnMore:{partial:"learnMore",context:f,executePartial:!0},feedback:{partial:"feedback",context:f,executePartial:!0}},data:e}))+"\n        </div>\n    </div>\n\n    ";if((j=d.each.call(a,a.sections,{hash:{},inverse:i.noop,fn:i.programWithDepth(b,e,a),data:e}))||j===0)c+=j;c+="\n\n</div>\n";return c},a,k),data:a}))||p===0)g+=p;g+="\n\n";if((p=d.partial.call(k,"learnMore",{hash:{},inverse:i.noop,fn:i.program(9,function(a,e){var b="";b+='\n    <a href="http://help.disqus.com/customer/portal/articles/666278-introducing-promoted-discovery-and-f-a-q-"\n        target="_blank">'+
o(d.t.call(a,gettext("Learn more"),{hash:{},data:e}))+"</a>\n";return b},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=d.partial.call(k,"feedback",{hash:{},inverse:i.noop,fn:i.program(11,function(a,e){var b="";b+='\n    <a href="https://www.surveymonkey.com/s/GHK872T" target="_blank">\n        '+o(d.t.call(a,gettext("give us feedback"),{hash:{},data:e}))+"</a>\n";return b},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=d.partial.call(k,"forumName",{hash:{},inverse:i.noop,fn:i.program(13,function(a,e){var b=
"",c;b+="\n    <strong>";(c=d.name)?c=c.call(a,{hash:{},data:e}):(c=a.name,c=typeof c===r?c.apply(a):c);b+=o(c)+"</strong>\n";return b},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=d.partial.call(k,"discoveryCollection",{hash:{},inverse:i.noop,fn:i.program(15,function(a,b){var f="",c;f+="\n    ";if((c=d.each.call(a,a.collection,{hash:{},inverse:i.noop,fn:i.programWithDepth(e,b,a),data:b}))||c===0)f+=c;f+="\n";return f},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=d.partial.call(k,"linkAttributes",{hash:{},
inverse:i.noop,fn:i.program(32,function(a,b){var e="",c;e+='\n    href="';(c=d.redirectUrl)?c=c.call(a,{hash:{},data:b}):(c=a.redirectUrl,c=typeof c===r?c.apply(a):c);e+=o(c)+'" ';if((c=d["if"].call(a,a.brand,{hash:{},inverse:i.noop,fn:i.program(33,A,b),data:b}))||c===0)e+=c;e+="\n";return e},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=d.partial.call(k,"discoveryContentPreview",{hash:{},inverse:i.noop,fn:i.program(35,function(a,e){var D;var w;var u;var b="",c;b+="\n    <a ";if((c=i.invokePartial(h.linkAttributes,
"linkAttributes",a,d,h,e))||c===0)b+=c;b+=' class="top-comment" data-role="discovery-top-comment">\n        <img src="'+o((w=(u=(c=(c=a.preview,c==null||c===!1?c:c.author),c==null||c===!1?c:c.avatar),c=u,c==null||c===!1?c:c.cache),c=w,typeof c===r?c.apply(a):c))+'" alt="'+o(d.t.call(a,gettext("Avatar"),{hash:{},data:e}))+'" data-role="discovery-avatar">\n        <p><span class="user" data-role="discovery-top-comment-author">'+o((D=(c=(c=a.preview,c==null||c===!1?c:c.author),c==null||c===!1?c:c.name),
c=D,typeof c===r?c.apply(a):c))+'</span> &#8212; <span data-role="discovery-top-comment-snippet" class="line-truncate" data-line-truncate="3">'+o((c=(c=a.preview,c==null||c===!1?c:c.plaintext),typeof c===r?c.apply(a):c))+"</span></p>\n    </a>\n";return b},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=d.partial.call(k,"discoveryPostCount",{hash:{},inverse:i.noop,fn:i.program(37,function(a,b){var e="",c;e+="\n    ";if((c=d["if"].call(a,a.posts===1,{hash:{},inverse:i.program(40,C,b),fn:i.program(38,B,b),
data:b}))||c===0)e+=c;e+="\n";return e},a),data:a}))||p===0)g+=p;g+="\n";return g})})();
DISQUS.define("discovery.collections",function(){var l=DISQUS.JSON,g=_.strip,k=DISQUS.use("discovery.helpers"),d=DISQUS.use("discovery.models"),h=Backbone.Collection.extend({url:function(a){return DISQUS.api.getURL(a)},fetch:function(a){a=a||{};a.reset=!0;return Backbone.Collection.prototype.fetch.call(this,a)},parse:function(a){return a.response}}),a=function(a){var b=a.prototype;return a.extend({url:function(){return b.url.call(this,"discovery/listTopPost.json")},parse:function(a){for(var a=b.parse.call(this,
a),e=0,f=a.length;e<f;e++)a[e].plaintext=g(a[e].message);return a}})}(h),b=function(a){var b=a.prototype;return a.extend({initialize:function(){this.model=d[this.modelName];this.getBanditJSON=_.memoize(this.getBanditJSON)},parse:function(a){a=b.parse.call(this,a);if("bandit"in a)this.bandit=a.bandit,a=a.results;if(!_.isArray(a))return[];return a},getBanditJSON:function(){return l.stringify(this.bandit)}})}(h),q=function(a){var b=a.prototype;return a.extend({modelName:"RelatedThread",url:function(){return b.url.call(this,
"discovery/listRelated.json")},parse:function(a,e){return this.rejectInvalid(b.parse.call(this,a),e.sourceThread)},rejectInvalid:function(a,b){return _.filter(a,function(a){if(a.id==b.id||a.link==b.link)return this.reportInvalid(a,"Link or id of related thread points back to thread on this page (circular reference)"),!1;if(a.title.search(/^https?:\/\//)===0)return this.reportInvalid(a,"Title looks like a url (begins with http:// or https://)"),!1;return!0},this)},reportInvalid:function(a,b){var e=
k.log;e("An organic link failed validation:",a.title,a.link,"(id =",a.id+")");e("Reason:",b)}})}(b),f=function(a){var b=a.prototype;return a.extend({modelName:"Advertisement",url:function(){return b.url.call(this,"discovery/listPromoted.json")}})}(b),m=function(a){var b=a.prototype;return a.extend({modelName:"TempestAdvertisement",url:"//tempest.services.disqus.com/listPromoted",fetch:function(a){a=a||{};a.dataType="jsonp";a.data=a.data||{};if(_.has(a.data,"limit"))a.data.count=a.data.limit,delete a.data.limit;
_.has(a.data,"thread")&&delete a.data.thread;return b.fetch.call(this,a)}})}(f),a={PostCollection:a,RelatedThreadCollection:q,AdvertisementCollection:f,TempestAdvertisementCollection:m};if(DISQUS.testing)a.BaseCollection=h,a.BaseContentCollection=b;return a});
DISQUS.define("discovery.helpers",function(l,g){var k=!1,d=!1,h=function(){};l.console&&(h=function(){if(d){var a=_.toArray(arguments);a.unshift("[Discovery]");l.console.log.apply?l.console.log.apply(l.console,a):l.console.log(a.join(" "))}});return{config:function(a){k=!!a.lineTruncationEnabled;d=!!a.consoleLoggingEnabled},isMobile:function(){return DISQUS.browser.mobile},log:h,allowLog:function(a){if(a===g)return d;d=!!a},allowLineTruncate:function(a){if(a===g)return k;k=!!a},lineTruncate:function(a,
b){function q(){return d.scrollHeight-d.offsetHeight>0.2*j}function f(){e.lastChild&&!_.contains(["...","\u2026"],e.lastChild.nodeValue)&&(g=e.appendChild(l.document.createTextNode(" "+t)),q()&&(e.removeChild(g),e.removeChild(e.lastChild),f()))}if(k){var m=DISQUS.logError||function(){};if(!a.closest("body").length)return void m("lineTruncate called on el not on DOM");if(a.text().length<1)return void m("lineTruncated called on empty el");if(_.any(a.children(),function(a){return a.nodeType!==3}))return void m("lineTruncate called on non-flat el");
var e=a[0],d=e;if(a.css("display")!=="block")for(;d.parentNode;)if(d=d.parentNode,$(d).css("display")==="block")break;var j=parseFloat(a.css("font-size"),10);if(q()){var b=b||{},m=b.lines||1,t=b.ellipsis,g,n=a.text();if(n.length){var s=a.width()/j,m=parseInt(s*m,10),n=n.split(/\s/),s=0;a.empty();for(var h=0,u=n.length;h<u;h++){s+=n[h].length+1;if(s>=m)break;e.appendChild(document.createTextNode(" "+n[h]))}if(q()){do g=e.removeChild(e.lastChild);while(q())}else{do g=e.appendChild(document.createTextNode(" "+
n[h++]));while(!q()&&h<u);e.removeChild(g)}t&&(_.isString(t)||(t="\u2026"),f())}}}},balancedPartition:function(a){var b=_.keys(a),q=Math.floor(_.reduce(a,function(a,b){return a+b},0)/2),f=b.length+1;q+=1;var m=Array(f),e,d;for(e=0;e<f;e++)m[e]=Array(q),m[e][0]={};for(d=1;d<q;d++)m[0][d]=!1;var j,g,h,n={};for(d=1;d<q;d++)for(e=1;e<f;e++){j=b[e-1];g=a[j];h=_.clone(m[e-1][d]);if(!h&&g<=d&&(h=_.clone(m[e-1][d-g])))h[j]=g,n=h;m[e][d]=h}return[n,_.omit(a,_.keys(n))]}}});
DISQUS.define("discovery.models",function(){var l=DISQUS.use("time"),g=function(a){var b=a.prototype;return a.extend({defaults:{redirectUrl:null,signedUrl:null,userId:null,sourceThreadId:null,forumId:null,forum:null,majorVersion:null,requestBin:null},redirectPayload:function(){var a={url:this.get("signedUrl"),imp:DISQUS.juggler.impId,forum_id:this.get("forumId"),forum:this.get("forum"),thread_id:this.get("sourceThreadId"),major_version:this.get("majorVersion")};if(this.has("requestBin"))a.bin=this.get("requestBin");
if(this.has("userId"))a.user_id=this.get("userId");if(this.collection&&this.collection.bandit)a.bandit=this.collection.getBanditJSON();return a},redirectUrl:function(){var a=this.get("redirectUrl"),b=this.redirectPayload();return DISQUS.serialize(a,b)},toJSON:function(){var a=b.toJSON.call(this);a.redirectUrl=this.redirectUrl();return a},toString:function(){return this.get("title")+" "+this.get("link")+" (id = "+this.id+")"}})}(Backbone.Model),k=function(a){var b=a.prototype;return a.extend({defaults:_.defaults({createdAgo:!1},
b.defaults),initialize:function(a,b){if(b&&b.humanFriendlyTimestamp){var d=l.assureTzOffset(this.get("createdAt")),d=moment(d,l.ISO_8601);this.set("createdAgo",d.fromNow())}},redirectPayload:function(){var a=b.redirectPayload.call(this);_.extend(a,{thread:this.id,zone:"internal_discovery"});return a},toJSON:function(){var a=b.toJSON.call(this);if(a.preview)a.preview=a.preview.toJSON();return a},toString:function(){return"organic link: "+b.toString.call(this)}})}(g),d=function(a){var b=a.prototype;
return a.extend({idAttribute:"body_id",defaults:_.defaults({brand:null,headline:null,text:null,url:null,advertisement_id:null,body_id:null,mobile:!0},b.defaults),get:function(a){if(a==="title")return this.attributes.headline;if(a==="link")return this.attributes.url;return b.get.call(this,a)},redirectPayload:function(){var a=b.redirectPayload.call(this);_.extend(a,{zone:"promoted_discovery",advertisement_id:this.get("advertisement_id")});if(this.has("body_id"))a.body_id=this.get("body_id");return a},
toJSON:function(){var a=b.toJSON.call(this);a.title=a.headline;a.link=a.url;return a},toString:function(){return"promoted link: "+b.toString.call(this)}})}(g),h=function(a){return a.extend({idAttribute:"advertisement_id",parse:function(a){a.signedUrl=a.signed_url;delete a.signed_url;return a}})}(d),k={RelatedThread:k,Advertisement:d,TempestAdvertisement:h};if(DISQUS.testing)k.BaseContentModel=g;return k});
DISQUS.define("discovery",function(){var l=DISQUS.use("discovery.collections"),g=DISQUS.use("discovery.views"),k=DISQUS.use("discovery.helpers"),d=Backbone.Model.extend({defaults:{name:"promoted",inlineMeta:!0,contentPreviews:!1,promotedEnabled:!0,topPlacementEnabled:!1,redirectUrl:"//redirect.disqus.com/url",listRelatedLimit:null,listPromotedLimit:null,httpTimeout:1E4,sourceThread:null,sourceForum:null,useNewAdserver:!1,help:!1,display:!1,columnEveningEnabled:!0,numColumns:2,minPerColumn:1,maxPerColumn:4,
toleranceCoefficient:1.2,minWidthForColumnLayout:440,containerId:"discovery",topPlacementContainerId:"discovery-top",innerContainerName:"discovery-main",sectionNames:["col-organic","col-promoted"],collectionTagName:"ul",collectionClassName:"discovery-posts",consoleLoggingEnabled:DISQUS.debug,lineTruncationEnabled:!0,session:null,js:null,css:null},initialize:function(){var a=this;a.createDataReferences();a.configure();a.once("change:display",function(){a.onComplete()});_.bindAll(a,"getContentPreviews",
"validateData","showData");a.run()},configure:function(){var a=this;a.set("innerContainerId",a.get("innerContainerName")+"-"+a.cid);a.set("sectionIds",_.map(a.get("sectionNames"),function(b){return b+"-"+a.cid}));var b=a.get("session");a.get("topPlacementEnabled")&&b.isAnonymous()&&a.set("containerId",a.get("topPlacementContainerId"))},commonClickMetadata:function(){var a=this.get("sourceThread"),b=this.get("sourceForum"),a={redirectUrl:this.get("redirectUrl"),sourceThreadId:a.id,forumId:b.pk,forum:b.id,
majorVersion:this.majorVersion(),requestBin:this.get("requestBin")};if((b=this.get("session"))&&b.isRegistered())a.userId=b.user.id;return a},augmentModels:function(a){a.invoke("set",this.commonClickMetadata())},createDataReferences:function(){this.collections=[];this.threads=new l.RelatedThreadCollection;this.collections.push(this.threads);if(this.get("promotedEnabled"))this.ads=new (this.get("useNewAdserver")?l.TempestAdvertisementCollection:l.AdvertisementCollection),this.collections.push(this.ads);
_.invoke(this.collections,"on","reset",this.augmentModels,this)},run:function(){var a=_.bind(this.onComplete,this);this.getData().then(this.validateData).then(this.showData).otherwise(a)},generateFetchOptions:function(){var a=this.get("numColumns");return{timeout:this.get("httpTimeout"),data:{thread:this.get("sourceThread").id,limit:a/this.collections.length*this.get("maxPerColumn")},sourceThread:this.get("sourceThread")}},getDataOrganic:function(){var a=this.generateFetchOptions();a.humanFriendlyTimestamp=
!0;if(this.has("listRelatedLimit"))a.data.limit=this.get("listRelatedLimit");a=when(this.threads.fetch(a));this.get("contentPreviews")&&(a=a.then(this.getContentPreviews));return a},getDataPromoted:function(){var a=this,b=this.generateFetchOptions();if(a.has("listPromotedLimit"))b.data.limit=a.get("listPromotedLimit");var d=when(a.ads.fetch(b));return d.then(function(b){b=b.bin;if(!b)return d;if(a.has("requestBin"))return d;a.set("requestBin",b);_.invoke(a.collections,"invoke","set","requestBin",
b);return a.handleExperiment(b)})},getData:function(){var a=this.getDataOrganic();if(!this.get("promotedEnabled"))return a;var b=this.getDataPromoted();return when.join(a,b)},handleExperiment:function(a){if(a.substring(0,31)==="embed:discovery:tempest:taboola"){a=a.substring(31);if(this.experimentHandlers[a])this.experimentHandlers[a]();this.set("experimentVariant",a);return this.getDataPromoted()}},experimentHandlers:{taboola:function(){var a=this.ads;a.off();this.ads=new l.TaboolaAdvertisementCollection;
this.collections.splice(_.indexOf(this.collections,a),1,this.ads);this.ads.on("reset",this.augmentModels)}},getContentPreviews:function(){var a=this.threads.pluck("id"),b=this.collections.length,d=this.get("numColumns"),f=this.get("minPerColumn");if(a.length<d/b*f)return when.resolve();this.previews=new l.PostCollection;return(this.listTopPostRequest=when(this.previews.fetch({data:{thread:a},timeout:this.get("httpTimeout")}))).then(_.bind(this.attachPreviews,this))},attachPreviews:function(){var a=
this;a.previews.each(function(b){var d=b.get("thread");(d=a.threads.get(d.id||d))&&d.set("preview",b)})},validateCollections:function(){for(var a=this.collections,b=a.length,d=this.get("numColumns"),f=this.get("minPerColumn"),m,e;b>0;)if(e=d/a.length*f,m=a[--b],m.length<e)a.splice(b,1),b=a.length;b=a.length;if(b>0){d=d/b*this.get("maxPerColumn");for(f=0;f<b;f++)m=a[f],m.length>d&&m.reset(m.slice(0,d))}},validateData:function(){k.isMobile()&&this.ads&&this.ads.length>0&&this.ads.remove(this.ads.where({mobile:!1}));
this.validateCollections();if(this.collections.length===0)throw"Not enough data";},showData:function(){function a(a){_.extend(this,a);this.appContext=b.toJSON()}var b=this,d=document.getElementById(b.get("containerId"));if(!d)throw"No container on the DOM";d=b.mainView=new g.MainView(new a({el:d,model:b}));d.render();var f=b.get("sectionIds"),m=b.get("collectionTagName"),e=b.get("collectionClassName");b.views=_.map(b.collections,function(b,d){return new g.BaseCollectionView(new a({collection:b,el:$("#"+
f[d]+" "+m+"."+e)}))});b.views.length===2&&d.$el.find("#"+b.get("innerContainerId")).addClass("doublesection");_.invoke(b.views,"render");if(b.get("columnEveningEnabled")&&d.$el.width()>b.get("minWidthForColumnLayout"))(new g.TwoColumn({views:b.views,fudge:this.get("toleranceCoefficient")})).render();else{var v=_.min(_.pluck(b.collections,"length"));_.each(b.views,function(a){for(;a.collection.length>v;)a.collection.pop()})}b.set("display",!0)},onComplete:function(a){var b=k.log;if(this.onCompleteCalled)return b("Error: Final reporting function called more than once");
this.onCompleteCalled=!0;a&&b("It looks like there was a problem:",a);this.report()},report:function(){var a=k.log,b=this.snapshot(),d=DISQUS.juggler.client("juggler");if(!d)return void a("Cannot report app state, no client found");a("Sending analytics data about this Discovery impression:");a("init_discovery: ",b);d.emit("init_discovery",b);this.get("darkJester")&&DISQUS.juggler.client("jester",!0).emit("init_discovery",b)},majorVersion:function(){return this.get("promotedEnabled")?"midway":"metadata"},
snapshot:function(){var a=this.collections,b=this.threads,b={major_version:this.majorVersion(),internal_organic:b.length,external_organic:0,promoted:0,display:this.get("display"),placement:this.get("containerId")===this.get("topPlacementContainerId")?"top":"bottom"};if(this.has("requestBin"))b.bin=this.get("requestBin");if(this.get("promotedEnabled")){var d=this.ads;_.extend(b,{promoted:d.length,promoted_ids:DISQUS.JSON.stringify(d.pluck("advertisement_id"))})}a=_.extend.apply(_,[{}].concat(_.pluck(a,
"bandit")));if(!_.isEmpty(a))b.bandit=DISQUS.JSON.stringify(a);return b}}),h={};if(DISQUS.testing)h.DiscoveryApp=d;h.init=function(a){var b=_.object(_.map(["lineTruncationEnabled","consoleLoggingEnabled"],function(b){return b in a?[b,a[b]]:[b,d.prototype.defaults[b]]}));k.config(b);return new d(a)};return h});
DISQUS.define("discovery.views",function(){var l=DISQUS.use("discovery.helpers"),g=Backbone.View.extend({initialize:function(a){if(a&&a.appContext)this.appContext=a.appContext},getTemplateContext:function(){if(!this.appContext)return{};return{variant:this.appContext}},template:function(a,b){b=b||this.templateName;return DISQUS.renderBlock(b,a)}}),k=function(a){var b=a.prototype;return a.extend({events:{"click [data-redirect]":"handleClick"},handleClick:function(a){this.swapHref(a.currentTarget)},
swapHref:function(a){a.setAttribute("data-href",a.getAttribute("href"));a.setAttribute("href",a.getAttribute("data-redirect"));_.delay(function(){a.setAttribute("href",a.getAttribute("data-href"))},100)},templateName:"discoveryCollection",initialize:function(a){b.initialize.call(this,a);this.elementsSelector="li.discovery-post";this.$elements=this.$el.find(this.elementsSelector);a=this.collection;a.on("remove",this.remove,this);a.on("reset",this.render,this)},truncate:function(){this.$el.find(".line-truncate").each(function(a){a=
$(a);l.lineTruncate(a,{lines:a.attr("data-line-truncate"),ellipsis:!0})})},getTemplateContext:function(){var a=b.getTemplateContext.call(this);a.collection=this.collection.toJSON();var d=this.collection.at(0),f=d.has("id")?"organic-":"promoted-",g=d.idAttribute;_.each(a.collection,function(a){a.domIdSuffix=a[g];a.domIdSuffix=f+a.domIdSuffix});return a},render:function(){this.$el.html(this.template(this.getTemplateContext()));this.$elements=this.$el.find(this.elementsSelector);this.truncate();return this},
remove:function(a,b,d){if(arguments.length===0)return g.prototype.remove.call(this);var f=_.toArray(this.$elements),m=f.splice(d.index,1)[0];$(m).remove();this.$elements=$(f);return this}})}(g),d=function(a,b){this.modelIds=a||[];this.$elements=$(b||[])};_.extend(d.prototype,{height:function(){var a=this;a.heights=[];var b=$(a.$elements),e=b.first().offset().top,e=function(){var a=b.last().offset();return a.top+a.height}()-e,d=0;_.each(b,function(b){b=$(b).height();a.heights.push(b);d+=b});this.interstice=
(e-d)/(b.length-1);return e}});var h=function(){this.divideIntoColumns=function(){var a=this,b=a.subviews[0];a.left=new d;a.right=new d;var e=0;b.collection.each(function(d,j){var g=e++%2===0?"left":"right";a[g].modelIds.push(d.id);Array.prototype.push.call(a[g].$elements,b.$elements[j])})};this.removeOneFromColumn=function(a,b){var e=_.chain(a.modelIds).map(function(b,e){return[b,a.heights[e]]}).sortBy(function(a){return-1*a[1]}).find(function(a){return a[1]<=b}).value()[0],d=this.subviews[0].collection,
j=d.models,g=d.get(e),h=j.indexOf(g),e=[[],[]],n,s=j.length;for(n=0;n<s;n++)e[n%2].push(j[n]);j=e[h%2];j.splice(_.indexOf(j,g),1);j=[];g=(h+1)%2;for(n=0;n<s-1;n++)j.push(e[(n+g)%2].shift());d.reset(j)};this.balanceColumns=function(){var a=this.subviews[0],b=a.collection,e={};b.each(function(b,d){e[d]=a.$elements[d]});var d=l.balancedPartition(e),d=_.sortBy(d,"length"),g=d[0],h=b.models,k=Array(h.length);_.each(d[1],function(a,b){k[2*b]=h[b]});_.each(g,function(a,b){k[2*b+1]=h[b]});b.reset(h)};this.shortenColumn=
function(a,b){this.subviews[0].collection.length%2!==0&&a===this.left?this.removeOneFromColumn(a,this.fudge*b):this.balanceColumns()}},a=function(){this.divideIntoColumns=function(){var a=this.subviews,b=a[0],a=a[1];this.left=new d(b.collection.pluck(b.collection.model.prototype.idAttribute),b.$elements);this.right=new d(a.collection.pluck(a.collection.model.prototype.idAttribute),a.$elements)};this.shortenColumn=function(a,b){for(var e=a===this.left?this.right:this.left,d=b/e.$elements.length,g=
(a===this.left?this.subviews[0]:this.subviews[1]).collection,h=_.chain(a.modelIds).map(function(b,e){return[b,a.heights[e]]}).sortBy(function(a){return a[1]}).value(),k=[],n=0,l=b,l=d;h.length;){var q=h.pop(),u=q[0],q=q[1]+a.interstice;n+q>b&&(e=a);l=Math.abs(b-(n+q));l/=e.$elements.length;l>=d||(d=l,l=a.modelIds.indexOf(u),a.modelIds.splice(l,1),Array.prototype.splice.call(a.$elements,l,1),n+=q,k.push(u))}g.remove(k)}},b=function(b){this.fudge=b.fudge;this.subviews=b.views.slice(0,2);this.subviews.length===
1?h.call(this):a.call(this)};_.extend(b.prototype,{ascendingByHeight:function(){var a=this.left,b=this.right,a=[[a,a.height()],[b,b.height()]];return _.sortBy(a,function(a){return a[1]})},evenColumns:function(a){var b=this.ascendingByHeight(),e=b[0][0],d=b[0][1],g=b[1][0],b=b[1][1];if(d!==b){var d=b-d,h=this.fudge*d,b=_.find(g.heights,function(a){return a+g.interstice<h});if(!a&&b)return this.shortenColumn(g,d),this.divideIntoColumns(),this.evenColumns("do not recurse again");this.increaseMargins(e,
d)}},increaseMargins:function(a,b){var e=b/a.$elements.length;_.each(a.$elements,function(a){var a=$(a),b=parseInt(a.css("margin-bottom"),10)+e;a.css("margin-bottom",b+"px")});(a===this.left?this.right:this.left).$elements.css("clear",a===this.right?"left":"right")},render:function(){this.divideIntoColumns();this.evenColumns();return this}});var q=function(a){var b=a.prototype;return a.extend({templateName:"discoveryMain",events:{"click [data-action=discovery-help]":function(a){a.preventDefault();
this.model.set("help",!0)},"click [data-action=discovery-help-close]":function(a){a.preventDefault();this.model.set("help",!1)}},toggleHelp:function(a){this.$el.find("#discovery-note").toggle();a.trigger("resize")},initialize:function(a){b.initialize.call(this,a);this.model.on("change:display",this.show,this);this.model.on("change:help",this.toggleHelp,this);this.$el.css({position:"absolute",visibility:"hidden",display:"block"})},createSections:function(){var a=this.model,b=DISQUS.discovery.collections,
d=b.RelatedThreadCollection,f=b.AdvertisementCollection,g=a.get("sectionNames"),h=a.get("sectionIds");return _.map(a.collections,function(a,b){var e;a instanceof d?e="organic":a instanceof f&&(e="promoted");return{id:h[b],className:g[b],type:e}})},render:function(){var a=this.model,b=this.createSections();this.$el.html(this.template({id:a.get("innerContainerId"),sections:b,forum:a.get("sourceForum"),session:a.get("session").toJSON()}))},show:function(a){a.get("display")&&(this.$el.css({position:"static",
visibility:"visible"}),a.trigger("resize"))}})}(g);return{BaseCollectionView:k,TwoColumn:b,MainView:q}});