
alias 'www__'='clear;pwd;cd ~/zdotfiles/link/;ls -alX'
    alias 'www__00'='clear;pwd;cd ~/zdotfiles/link/;ls -alX'
    alias 'www__11'='clear;pwd;cd ~/zdotfiles/1;ls -X'
    alias 'www__22'='clear;pwd;cd ~/zdotfiles/2;ls -X'
    alias 'www__33'='clear;pwd;cd ~/zdotfiles/3;ls -X'
    alias 'www__44'='clear;pwd;cd ~/zdotfiles/4;ls -X'
    alias 'www__55'='clear;pwd;cd ~/zdotfiles/5;ls -X'
    alias 'www__66'='clear;pwd;cd ~/zdotfiles/6;ls -X'
    alias 'www__77'='clear;pwd;cd ~/zdotfiles/7;ls -X'
    alias 'www__88'='clear;pwd;cd ~/zdotfiles/8;ls -X'
    alias 'www__99'='clear;pwd;cd ~/zdotfiles/9;ls -X'

    alias 'www__clr'='clear;pwd;ls'
    alias 'www__gf'='git ls-files | grep'
    alias 'www__kla'="ls -a | grep '^\.'"
    alias 'www__klj'='ls -a | grep "^\.\(.*\)n$"'
    alias 'www__l'='ls -ltr'
    alias 'www__la'='ls -A'
    alias 'www__le='ls --sort'=extension'
    alias 'www__lf'='ls -Gl | grep ^d'
    alias 'www__lh'='ls -a | egrep "^\."'
    alias 'www__lhd'='ls -A | egrep "^\."'
    alias 'www__ll'='ls -l'
    alias 'www__lla'='ls -lhFA'
    alias 'www__lll'='ls -alF'
    alias 'www__lr'='ls -R'
    alias 'www__lrt'='ls -lart'
    alias 'www__ls='ls --color'=tty'
    alias 'www__lsd'='ls -Gal | grep ^d'
alias 'www__build'='mkdir build ; cd build && cmake .. && make ; cd .. && ls'

    alias 'www__lt='ls --sort'=time'
    alias 'www__netlisteners'='lsof -i -P | grep LISTEN'
    alias 'www__wkl'='cd $HOME/.config/autokey/data;ls'
    alias 'www__wlrs_sizels'='ls -lhR | grep -e "total\|:\$"' # list and get size
    alias 'www__ww-lsusb-grep-Sony'='lsusb| grep Sony'
    alias 'www__ww_wlz'='ls -a | egrep "zsh|vim|sh|rc"'
