#!/usr/bin/env zsh


export LC_ALL=en_US.UTF-8

source $HOME/zdotfiles/1/.zsh/checks.zsh
source $HOME/zdotfiles/1/.zsh/colors.zsh
source $HOME/zdotfiles/1/.zsh/completion.zsh
source $HOME/zdotfiles/1/.zsh/exports.zsh
source $HOME/zdotfiles/1/.zsh/functions.zsh

source $HOME/zdotfiles/1/.zsh/history.zsh

source $HOME/zdotfiles/1/.zsh/prompt.zsh

source $HOME/zdotfiles/1/.zsh/setopt.zsh
source $HOME/zdotfiles/1/.zsh/zsh_hooks.zsh

#source $HOME/zdotfiles/1/.zsh/arabic_alias.zsh
#source $HOME/zdotfiles/1/z_arabic.sh

# source $HOME/zdotfiles/1/.zsh/config


#source ~/zdotfiles/1/z_arabic.sh
# PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
#setopt prompt_subst

#source $HOME/zdotfiles/link/1.sh
. /usr/local/lib/python2.7/dist-packages/powerline/bindings/zsh/powerline.zsh
