#!/usr/bin/env bash



zdotfiles_link() {
    if [ -d $src ]; then
        for f in $src; do
    # TODO:TEST
    lnif $dest/$f $src/$f
    done
    fi
    unset f
}

zbkup() {
    for i in $dir_DOTFILES ; do [ -e "$i" ] && [ ! -L "$i" ] && mv "$i"
"$(echo $i | sed 's/\(\/home\/\(.*\)\/\(.*\)/\1\/\2\/bkup\/\3_BKUP/')"; done
        success "Done!"
        ret="$?"
        $success "$1"
        debug
    unset i
}



do_backup() { today=`date +%Y%m%d_%s`
        [ -e "$i" ] && [ ! -L "$i" ] && mv "$i" "$BKUP/$i.$today";
        success "Moved $i to "
        ret="$?"
        success "$1"
        debug
}

check_bkup_dir() { if [ -d $HOME/bkup ]; then
        mkdir -p $HOME/bkup
        success "mkdir $HOME/bkup"
        BKUP=$HOME/bkup
    fi
}

check_zdotfiles_dir() {
    if [ -d /home/w/zdotfiles ]; then success "zdotfiles is available"
    else error "No zdotfilesc" fi }

usage() { cat << EOF
    usage: $0 options

    This script make and install Blender
    EOF
}

ll_dotfiles_dir() {
    ls al | wc -l
}
dir_DOTFILES=$(cd ~;ls .*)
src=$HOME/zdotfiles/link
BKUP=$HOME/bkup

z_restore() {
    for i in $HOME/bkup/.*; do
        [ -e "$i" ] && mv "$i" "$(echo $i | sed 's/\(\/home\)\/\(.*\)\/\(.*\)_bkup\/\(.*\)/\1\/\2\3/')"
    done
    ret="$?" success "$1" debug
}


restore_x_bkup() {
    for f in $LINKS; do
        source="${LINKS}/$f"
        target="${HOME}/$f"
    #if [ "$1" = "restore" ]; then
        #echo "# Restore backups if found"
    #fi

    if [ -e "${target}_bkup" ] && [ -L "${target}" ]; then
        unlink "${target}"
        mv "$target.dotfile.bak" "$target"
    fi
    #else
        echo "# Link files"
    if [ -e "${target}" ] && [ ! -L "${target}" ]; then
            mv "$target" "$target.dotfile.bak"
    #fi
         #TODO: fix recursive symlinks
        ln -sf "${source}" "${target}"
    fi
    done
}
