#!/bin/bash

sudo apt-get install liblink-grammar4-dev
sudo apt-get install cmake
sudo apt-get install swig
pip install pylinkgrammar
#>>> from pylinkgrammar.linkgrammar import Parser
#>>> p = Parser()
#>>> linkages = p.parse_sent("This is a simple sentence.")
#>>> len(linkages)
#>>> priis not changed , you can see the README.md in each colornt linkages[0].diagram
Class wdcar
sort u
synmim
https://github.com/tazjel/sent-suggest/edit/master/sent-suggest.py
When The text was entered sort by

What filetype
what is the subject
type of email or  rsearch paper

Conflict : Model
Analysis : View
Resoltion : Controller

