#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)



zdotfiles_link() {
dir=$HOME
dest=$HOME/zdotfiles/link

if [ -d $dest ]; then
        for f in $dest ; do
           [ -x "$f" ] && echo "$f"

        done
        unset f
fi
}



# Here xfce is kept as default
case $1 in
        gnome) exec zdotfiles_link;;
        kde) exec startkde;;
        xfce);;
        *) exec startxfce4;;
esac
