#!/bin/bash
BB="\
acpi-support
akregator
amarok
apper
avahi-autoipd
avahi-daemon
bluedevil
bluez
bluez-cups
brltty
cdrdao
colord-kde
cryptsetup
cups
cups-bsd
cups-client
dragonplayer
fonts-kacst-one
fonts-lao
fonts-linuxlibertine
fonts-lklug-sinhala
fonts-nanum
fonts-sil-abyssinica
fonts-sil-padauk
fonts-thai-tlwg
fonts-tibetan-machine
gnupg-agent
gpgsm
gstreamer0.10-qapt
gtk2-engines-oxygen
gtk3-engines-oxygen
gwenview
hplip
ibus-qt4
im-config
k3b
kaccessible
kaddressbook
kamera
kamoso
kate
kcalc
kde-config-gtk-style
kde-config-tablet
kde-config-touchpad
kde-telepathy
kdegraphics-strigi-analyzer
kdenetwork-filesharing
kdepim-kresources
kdepim-runtime
kdepim-strigi-plugins
kdesudo
kerneloops-daemon
kio-mtp
kmag
kmail
kmousetool
knotes
kontact
konversation
korganizer
kpat
kppp
krdc
kscreen
ksystemlog
ktorrent
ktouchpadenabler
kuser
kwalletmanager
laptop-detect
libnss-mdns
libqca2-plugin-ossl
libreoffice-calc
libreoffice-impress
libreoffice-kde
libreoffice-style-oxygen
libreoffice-writer
mobile-broadband-provider-info
okular-extra-backends
oxygen-icon-theme
oxygencursors
partitionmanager
pcmciautils
phonon-backend-gstreamer
pinentry-qt4
plasma-widget-folderview
plasma-widget-kimpanel
plasma-widget-menubar
plasma-widget-message-indicator
plasma-widget-networkmanagement
plasma-widget-telepathy-chat
plasma-widgets-addons
plymouth-theme-tanglu-logo
policykit-desktop-privileges
polkit-kde-1
print-manager
printer-driver-c2esp
printer-driver-foo2zjs
printer-driver-min12xxw
printer-driver-ptouch
printer-driver-pxljr
printer-driver-sag-gdi
printer-driver-splix
pulseaudio-module-bluetooth
pulseaudio-module-x11
python-qt4-dbus
skanlite
tanglu-kde-settings-active
tanglu-kde-settings-netbook
tanglu-theme-kde
ttf-oxygen-font-family
ttf-wqy-microhei
udisks
upower
xcursor-themes
xdg-utils"



XX="\
arabeyes
fonts-arphic-bkai00mp
fonts-arphic-bsmi00lp
fonts-arphic-gbsn00lp
fonts-arphic-gkai00mp
fonts-arphic-ukai
fonts-arphic-uming
fonts-dejavu
fonts-dejavu-core
fonts-dejavu-extra
fonts-dzongkha
fonts-farsiweb
fonts-freefont-ttf
fonts-ipafont-gothic
fonts-ipafont-mincho
fonts-kacst
fonts-kacst-one
fonts-khmeros
fonts-khmeros-core
fonts-lao
fonts-liberation
fonts-lklug-sinhala
fonts-lmodern
fonts-manchufont
fonts-mgopen
fonts-nafees
fonts-nanum
fonts-nanum-coding
fonts-nanum-extra
fonts-opensymbol
fonts-sil-abyssinica
fonts-sil-ezra
fonts-sil-nuosusil
fonts-sil-padauk
fonts-sil-scheherazade
fonts-takao-gothic
fonts-takao-mincho
fonts-takao-pgothic
fonts-texgyre
fonts-thai-tlwg
fonts-tibetan-machine
fonts-tlwg-garuda
fonts-tlwg-kinnari
fonts-tlwg-loma
fonts-tlwg-mono
fonts-tlwg-norasi
fonts-tlwg-purisa
fonts-tlwg-sawasdee
fonts-tlwg-typewriter
fonts-tlwg-typist
fonts-tlwg-typo
fonts-tlwg-umpush
fonts-tlwg-waree
fonts-ubuntu-font-family-console
fonts-ukij-uyghur
fonts-unfonts-core
fonts-vlgothic"





#
sudo_apt_install()
{
    sudo apt-get install -y "$1";
}

#
install_list_packages()
{
    for DD in $XX;do
        echo "Now, install  $DD";
        sudo_apt_install $DD;
    done;
}



zinstall_list_packages()
{
    for pp  in $BB;do
        echo "Now, install  $PP";
        sudo_apt_install $PP;
    done;
}


zinstall_list_packages
install_list_packages
