source $HOME/zdotfiles/1/.zsh/al.zsh
source $HOME/zdotfiles/1/.zsh/checks.zsh
source $HOME/zdotfiles/1/.zsh/colors.zsh
source $HOME/zdotfiles/1/.zsh/completion.zsh
source $HOME/zdotfiles/1/.zsh/exports.zsh
source $HOME/zdotfiles/1/.zsh/functions.zsh
source $HOME/zdotfiles/1/.zsh/history.zsh
source $HOME/zdotfiles/1/.zsh/prompt.zsh
source $HOME/zdotfiles/1/.zsh/setopt.zsh
source $HOME/zdotfiles/1/.zsh/zsh_history
source $HOME/zdotfiles/1/.zsh/zsh_hooks.zsh
