source ~/zdotfiles/1/.zsh/aliases.zsh
source ~/zdotfiles/1/.zsh/al.zsh
source ~/zdotfiles/1/.zsh/checks.zsh
source ~/zdotfiles/1/.zsh/colors.zsh
source ~/zdotfiles/1/.zsh/completion.zsh
source ~/zdotfiles/1/.zsh/exports.zsh
source ~/zdotfiles/1/.zsh/functions.zsh
source ~/zdotfiles/1/.zsh/history.zsh
source ~/zdotfiles/1/.zsh/prompt.zsh
source ~/zdotfiles/1/.zsh/setopt.zsh
source ~/zdotfiles/1/.zsh/zsh_history
source ~/zdotfiles/1/.zsh/zsh_hooks.zsh
