source ~/zdotfiles/.zsh/al.zsh
source ~/zdotfiles/.zsh/checks.zsh
source ~/zdotfiles/.zsh/colors.zsh
source ~/zdotfiles/.zsh/completion.zsh
source ~/zdotfiles/.zsh/exports.zsh
source ~/zdotfiles/.zsh/functions.zsh
source ~/zdotfiles/.zsh/history.zsh
source ~/zdotfiles/.zsh/prompt.zsh
source ~/zdotfiles/.zsh/setopt.zsh
source ~/zdotfiles/.zsh/zsh_history
source ~/zdotfiles/.zsh/zsh_hooks.zsh
