#!/bin/bash


read -d '' String <<"EOF"
    Miall, Hugh, Oliver Ramsbotham and Tom Woodhouse.  (2011).   Contemporary Conflict Resolution. 3[rd] Edition.  Cambridge, UK:  Polity Press.

    Lederach, John Paul. (2005). The Moral Imagination:  the Art and Soul of Building Peace. Oxford, UK:  Oxford UP.

    Cheldelin, Druckman and Fast, eds.  (2008). Conflict, 2[nd] ed. London: Continuum Press.

    Pruitt, Dean and Kim, Sung Hee. (2003). Social Conflict: Escalation, Stalemate and Settlement (3[rd] edition). New York, NY: McGraw Hill.
    Cloke, Kenneth. (2008).   Conflict Revolution:  Mediating Evil, War, Injustice, and Terrorism. Santa Ana, CA:  Janis Publications.
    McDonald, John and Louise Diamond.  (1996).  Multi-Track Diplomacy:  a Systems Approach to Peace.  West Hartford, CT:  Kumarian Press.

    Tidwell, Alan C.  (2001).  Conflict Resolved?  London, UK:  Pinter Publishers.
EOF

wcar_textbooks() {echo $String | egrep -i --color=auto "$1"}


###########################

