
    #alias 'w'='clear;ls -X;pwd;echo -e "\t\t\t$(date)"'
    #alias 'w'='clear;ls -X;pwd;echo -e "\t\t\t$(date)"'
    #alias 'ما'='ls'
    #alias 'ما'='ls'

    alias '11'='clear;pwd;cd ~/zdotfiles/1;ls -X'
    alias '11'='clear;pwd;cd ~/zdotfiles/1;ls -X'
    alias '22'='clear;pwd;cd ~/zdotfiles/2;ls -X'
    alias '22'='clear;pwd;cd ~/zdotfiles/2;ls -X'
    alias '33'='clear;pwd;cd ~/zdotfiles/3;ls -X'
    alias '33'='clear;pwd;cd ~/zdotfiles/3;ls -X'
    alias '44'='clear;pwd;cd ~/zdotfiles/4;ls -X'
    alias '44'='clear;pwd;cd ~/zdotfiles/4;ls -X'
    alias '55'='clear;pwd;cd ~/zdotfiles/5;ls -X'
    alias '55'='clear;pwd;cd ~/zdotfiles/5;ls -X'
    alias '66'='clear;pwd;cd ~/zdotfiles/6;ls -X'
    alias '66'='clear;pwd;cd ~/zdotfiles/6;ls -X'
    alias '77'='clear;pwd;cd ~/zdotfiles/7;ls -X'
    alias '77'='clear;pwd;cd ~/zdotfiles/7;ls -X'
    alias '88'='clear;pwd;cd ~/zdotfiles/8;ls -X'
    alias '88'='clear;pwd;cd ~/zdotfiles/8;ls -X'
    alias '99'='clear;pwd;cd ~/zdotfiles/9;ls -X'
    alias '99'='clear;pwd;cd ~/zdotfiles/9;ls -X'
    alias 'kla'="ls -a | grep '^\.'"
    alias 'kla'="ls -a | grep '^\.'"
    alias 'klj'='ls -a | grep "^\.\(.*\)n$"'
    alias 'klj'='ls -a | grep "^\.\(.*\)n$"'
    alias 'w'='clear;ls -X;pwd;echo -e "\t\t\t$(date)"'
    alias 'w'='clear;ls -X;pwd;echo -e "\t\t\t$(date)"'
    alias 'wkl'='cd $HOME/.config/autokey/data;ls'
    alias 'wkl'='cd $HOME/.config/autokey/data;ls'
    alias 'wlrs_sizels'='ls -lhR | grep -e "total\|:\$"' # list and get size
    alias 'wlrs_sizels'='ls -lhR | grep -e "total\|:\$"' # list and get size
    alias 'wlv'='ls -a | grep vim'
    alias 'wlv'='ls -a | grep vim'
    alias 'wlz'='ls -a | grep zsh'
    alias 'wlz'='ls -a | grep zsh'
    alias 'ww-lsusb-grep-Sony'='lsusb| grep Sony'
    alias 'ww-lsusb-grep-Sony'='lsusb| grep Sony'
    alias build='mkdir build ; cd build && cmake .. && make ; cd .. && ls'
    alias build='mkdir build ; cd build && cmake .. && make ; cd .. && ls'
    alias clr='clear;pwd;ls'
    alias clr='clear;pwd;ls'
    alias gf='git ls-files | grep'
    alias gf='git ls-files | grep'
    alias l.='ls -d .* --color=auto'
    alias l.='ls -d .* --color=auto'
    alias l='ls -ltr'
    alias l='ls -ltr'
    alias la='ls -A'
    alias la='ls -A'
    alias le='ls --sort=extension'
    alias le='ls --sort=extension'
    alias lf='ls -Gl | grep ^d'
    alias lf='ls -Gl | grep ^d'
    alias lh='ls -a | egrep "^\."'
    alias lh='ls -a | egrep "^\."'
    alias lhd='ls -A | egrep "^\."'
    alias lhd='ls -A | egrep "^\."'
    alias ll='ls -l'
    alias ll='ls -l'
    alias lla='ls -lhFA'
    alias lla='ls -lhFA'
    alias lll='ls -alF'
    alias lll='ls -alF'
    alias lr='ls -R'
    alias lr='ls -R'
    alias lrt='ls -lart'
    alias lrt='ls -lart'
    alias ls='ls --color=tty'
    alias ls='ls --color=tty'
    alias lsd='ls -Gal | grep ^d'
    alias lsd='ls -Gal | grep ^d'
    alias lt='ls --sort=time'
    alias lt='ls --sort=time'
    alias netlisteners='lsof -i -P | grep LISTEN'
    alias netlisteners='lsof -i -P | grep LISTEN'
